/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW.telaEmprestimo;

import DAO.EmprestimoBiblioteca;
import MODEL.Emprestimo;
import VIEW.MenuOpcoes.menuOpcoes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eliria
 */
public class telaEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form telaEmprestimo
     */
    public telaEmprestimo() {
        initComponents();
        listarEmprestimos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeLeitor = new javax.swing.JTextField();
        txtNomeLivro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDataEmprestimo = new javax.swing.JTextField();
        btnFinalizarEmprestimo = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEmprestimo = new javax.swing.JTable();
        btnCarregarCampos = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoEmprestimo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoLivro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoLeitor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDataDevolucao = new javax.swing.JTextField();
        btnVoltarAoMenu = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emprestimo ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nome do Leitor");

        txtNomeLeitor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtNomeLeitor.setMargin(new java.awt.Insets(2, 12, 2, 6));

        txtNomeLivro.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtNomeLivro.setMargin(new java.awt.Insets(2, 12, 2, 6));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nome do Livro");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Data de empréstimo");

        txtDataEmprestimo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtDataEmprestimo.setMargin(new java.awt.Insets(2, 12, 2, 6));

        btnFinalizarEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFinalizarEmprestimo.setText("FINALIZAR");
        btnFinalizarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarEmprestimoActionPerformed(evt);
            }
        });

        tabelaEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabelaEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo do emprestimo","Leitor", "Livro", "Data Emprestimo", "Data Devolucao", "Codigo do livro", "Codigo do Leitor"
            }
        ));
        tabelaEmprestimo.setRowHeight(30);
        jScrollPane1.setViewportView(tabelaEmprestimo);

        btnCarregarCampos.setText("CARREGAR CAMPOS");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        btnLimparCampos.setText("LIMPAR CAMPOS");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Codigo");

        txtCodigoEmprestimo.setEditable(false);
        txtCodigoEmprestimo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtCodigoEmprestimo.setMargin(new java.awt.Insets(2, 12, 2, 6));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Codigo do livro");

        txtCodigoLivro.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtCodigoLivro.setMargin(new java.awt.Insets(2, 12, 2, 6));
        txtCodigoLivro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoLivroKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Codigo do Leitor");

        txtCodigoLeitor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtCodigoLeitor.setMargin(new java.awt.Insets(2, 12, 2, 6));
        txtCodigoLeitor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoLeitorKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Data de devolução");

        txtDataDevolucao.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtDataDevolucao.setMargin(new java.awt.Insets(2, 12, 2, 6));

        btnVoltarAoMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVoltarAoMenu.setText("VOLTAR AO MENU");
        btnVoltarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAoMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtCodigoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 242, Short.MAX_VALUE))
                            .addComponent(txtNomeLivro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtCodigoLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(568, 568, 568)
                .addComponent(btnFinalizarEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarAoMenu)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCarregarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparCampos)))
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarCampos)
                    .addComponent(btnLimparCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnFinalizarEmprestimo)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltarAoMenu)
                        .addGap(49, 49, 49))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1339, 795));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoLivroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoLivroKeyTyped
        String numeros = "0123456789";
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoLivroKeyTyped

    private void txtCodigoLeitorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoLeitorKeyTyped
        String numeros = "0123456789";
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoLeitorKeyTyped

    private void btnFinalizarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarEmprestimoActionPerformed
        createEmprestimo();
        listarEmprestimos();
        LimparCampos();
    }//GEN-LAST:event_btnFinalizarEmprestimoActionPerformed

    private void btnVoltarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAoMenuActionPerformed
        menuOpcoes opcoes = new menuOpcoes();

        opcoes.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnVoltarAoMenuActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
        carregarCampos();
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaEmprestimo().setVisible(true);
            }
        });
    }

    private void listarEmprestimos() {
        try {
            EmprestimoBiblioteca emprestimoBiblioteca = new EmprestimoBiblioteca();

            DefaultTableModel model = (DefaultTableModel) tabelaEmprestimo.getModel();

            model.setNumRows(0);

            for (Emprestimo emprestimo : emprestimoBiblioteca.mostraEmprestimos()) {
                model.addRow(new Object[]{
                    emprestimo.getId_emprestimo(),
                    emprestimo.getNome_leitor(),
                    emprestimo.getNome_livro(),
                    emprestimo.getData_emprestimo(),
                    emprestimo.getData_devolucao(),
                    emprestimo.getId_leitor(),
                    emprestimo.getId_livro()
                });
            }

            emprestimoBiblioteca.mostraEmprestimos();

        } catch (Exception e) {
            System.out.println("Erro " + e);
        }
    }

    private void createEmprestimo() {
        EmprestimoBiblioteca emprestimoBiblioteca = new EmprestimoBiblioteca();
        Emprestimo emprestimo = new Emprestimo();

        String nomeLeitor = txtNomeLeitor.getText();
        String nomeLivro = txtNomeLivro.getText();
        String data_devolucao = txtDataDevolucao.getText();
        String data_emprestimo = txtDataEmprestimo.getText();
        int id_leitor = Integer.parseInt(txtCodigoLeitor.getText());
        int id_livro = Integer.parseInt(txtCodigoLeitor.getText());

        emprestimo.setId_livro(id_livro);
        emprestimo.setData_emprestimo(data_emprestimo);
        emprestimo.setData_devolucao(data_devolucao);
        emprestimo.setId_leitor(id_leitor);
        emprestimo.setNome_livro(nomeLivro);
        emprestimo.setNome_leitor(nomeLeitor);

        emprestimoBiblioteca.createEmprestimo(emprestimo);
    }

    private void carregarCampos() {
        try {
            int linhaSelecionada = tabelaEmprestimo.getSelectedRow();

            if (linhaSelecionada < 0) {
                JOptionPane.showMessageDialog(null, "Por favor, selecione uma linha");
            } else {
               txtCodigoEmprestimo.setText(tabelaEmprestimo.getModel().getValueAt(linhaSelecionada, 0).toString());
               txtNomeLeitor.setText(tabelaEmprestimo.getModel().getValueAt(linhaSelecionada, 1).toString());
               txtNomeLivro.setText(tabelaEmprestimo.getModel().getValueAt(linhaSelecionada,2).toString());
               txtDataEmprestimo.setText(tabelaEmprestimo.getModel().getValueAt(linhaSelecionada, 3).toString());
               txtCodigoLivro.setText(tabelaEmprestimo.getModel().getValueAt(linhaSelecionada, 4).toString());
               txtCodigoLeitor.setText(tabelaEmprestimo.getModel().getValueAt(linhaSelecionada, 5).toString());
               txtDataDevolucao.setText(tabelaEmprestimo.getModel().getValueAt(linhaSelecionada, 6).toString());
            }
        } catch (Exception e) {
            System.out.println("Erro ao carregar campos: " + e);
        }

    }

    private void LimparCampos() {
        txtCodigoEmprestimo.setText("");
        txtCodigoLeitor.setText("");
        txtDataDevolucao.setText("");
        txtDataEmprestimo.setText("");
        txtNomeLeitor.setText("");
        txtNomeLivro.setText("");
        txtCodigoLivro.setText("");
        txtNomeLeitor.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JToggleButton btnFinalizarEmprestimo;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JToggleButton btnVoltarAoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEmprestimo;
    private javax.swing.JTextField txtCodigoEmprestimo;
    private javax.swing.JTextField txtCodigoLeitor;
    private javax.swing.JTextField txtCodigoLivro;
    private javax.swing.JTextField txtDataDevolucao;
    private javax.swing.JTextField txtDataEmprestimo;
    private javax.swing.JTextField txtNomeLeitor;
    private javax.swing.JTextField txtNomeLivro;
    // End of variables declaration//GEN-END:variables
}
